// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
        return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlng2sa6MzPycTrdxJCkRrGdCRBvJpj0Q',
    appId: '1:260846768353:android:83abc1d66285c0719727a0',
    messagingSenderId: '260846768353',
    projectId: 'peminjaman-lab-1c332',
    storageBucket: 'peminjaman-lab-1c332.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQtfCka1BeJFRV4-cTzNsiqd3CysoF7co',
    appId: '1:260846768353:ios:21338db53bfaf7cf9727a0',
    messagingSenderId: '260846768353',
    projectId: 'peminjaman-lab-1c332',
    storageBucket: 'peminjaman-lab-1c332.firebasestorage.app',
    iosBundleId: 'com.example.pblPeminjamanLab',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyARtiZlBBAdS0xKISmJFayiutt0U0uJUjw",
    authDomain: "peminjaman-lab-1c332.firebaseapp.com",
    projectId: "peminjaman-lab-1c332",
    storageBucket: "peminjaman-lab-1c332.firebasestorage.app",
    messagingSenderId: "260846768353",
    appId: "1:260846768353:web:29bb18f30a60d8a29727a0",
    measurementId: "G-FQRPPGYFJ3"
    );
}
